Test/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('category/', include('category.urls')),
    path('articl/', include('articl.urls')),
]

articl/urls.py
from django.urls import path,include
from articl import views
app_name='articl'
urlpatterns = [
    path(r'<int:articl_id>/', views.index , name='index' ),
    path(r'<int:articl_id>/leave_coment', views.leave_coment , name='leave_coment' ),
]

category/urls.py
from django.urls import path,include
from category import views
app_name='category'
urlpatterns = [
    path('', views.index , name='index' ),
    path(r'<int:category_id>/', views.category_detal , name='category_detal' ),
]

mainApp/urls.py
from django.urls import path,include
from mainApp import views

app_name='mainApp'
urlpatterns = [
    path(r'', views.index , name='index' ),
    path(r'/leave_coment', views.leave_email , name='leave_email' ),
]

articl/models.py
from django.db import models

# Create your models here.

category/models.py
from django.db import models

# Create your models here.

mainApp/models.py
from django.db import models

# Create your models here.
class Articlesnew(models.Model):
    title=models.CharField(max_length=120)
    text=models.TextField()
    category=models.TextField()
    views=models.IntegerField()
    img=models.ImageField()
    date=models.DateTimeField()

    def __str__(self):
        return self.title

class Slider_info(models.Model):
    title=models.CharField(max_length=120, verbose_name="Текст заголовка")
    btn_text=models.CharField(max_length=120, verbose_name="Текст кнопки")
    def __str__(self):
        return self.title

class Slider_image(models.Model):
    image = models.ImageField()
    slider_info = models.ForeignKey('Slider_info', on_delete=models.CASCADE)


class Category(models.Model):
    title=models.CharField(max_length=120,verbose_name="Назва категорії")
    slug=models.SlugField(unique=True)
    image = models.ImageField()
    text=models.TextField( verbose_name="Текст статі")
    def __str__(self):
        return self.title

class Mark(models.Model):
    name=models.CharField(max_length=120, verbose_name="Назва мітки")
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.name

class Article(models.Model):
    title=models.CharField(max_length=120, verbose_name="Заголовок статі")
    text=models.TextField( verbose_name="Текст статі")
    image = models.ImageField()
    slug=models.SlugField()
    category=models.ForeignKey('Category', on_delete=models.CASCADE ,verbose_name="Категорія")
    mark=models.ForeignKey('Mark', on_delete=models.CASCADE, verbose_name="Мітка")
    views=models.IntegerField()
    date=models.DateTimeField()
    def __str__(self):
        return self.title

class Cametn(models.Model):
    autor_name=models.CharField(max_length=120, verbose_name="Імя автора")
    text=models.TextField( verbose_name="Текст")
    articl=models.ForeignKey('Article', on_delete=models.CASCADE,related_name="com")
    


class Email(models.Model):
    name=models.CharField(max_length=120, verbose_name="Імя автора") 
    surname=models.CharField(max_length=120, verbose_name="Прізвище автора") 
    email=models.CharField(max_length=120, verbose_name="Email автора") 

articl/views.py
from django.shortcuts import render
from mainApp.models import Article,Cametn,Category,Mark,Slider_image,Slider_info
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
# Create your views here.
def index(request, articl_id): 
    try:
        article= Article.objects.get(id=articl_id)
    except:
        raise Http404("a")        
    coments=article.com.order_by('-id')[:10]
    return render(request,'articl/index.html',{'article':article, 'coments':coments})    


def leave_coment(request, articl_id): 
    try:
        article= Article.objects.get(id=articl_id)
    except:
        raise Http404("a")    


    article.com.create(autor_name=request.POST['name'],text=request.POST['text'])

    return HttpResponseRedirect(reverse('articl:index',args=(article.id,)))

category/views.py
from django.shortcuts import render
from mainApp.models import Article,Cametn,Category,Mark,Slider_image,Slider_info
from django.http import HttpResponseRedirect,Http404
# Create your views here.
def index(request):
    category= Category.objects.all()
    articl= Article.objects.all()
    return render(request,'category/index.html',{'category':category,'articl':articl})

def category_detal(request,category_id):
    try:
        category= Category.objects.get(id=category_id)
        
    except:
        raise Http404("cta")    
    try:
        
        article= Article.objects.all().filter(category=category_id)
    except:
        raise Http404("a")   
    return render(request,'category/category.html',{'category':category,'article':article})    

mainApp/views.py
from django.shortcuts import render
from django.template import loader
from mainApp.models import Article,Cametn,Category,Mark,Slider_image,Slider_info,Email
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
# Create your views here.

def index(request):
    articl = Article.objects.all().order_by('-views')[:10]
    category = Category.objects.all()
    
    context = {
        'articl': articl,
        'category': category,
    }
    return render(request,'mainApp/index.html',context)

def leave_email(request): 
    try:
        email= Email.objects.create(name=request.POST['name'],surname=request.POST['surname'],email=request.POST['email'])
    except:
        raise Http404("a")    


    return HttpResponseRedirect(reverse('mainApp:index'))

articl/templates/articl/inculudes/category.html
{%block category%}

       
   

<a href=""><h3>{{category.title}}</h3></a>




        {%endblock%}

articl/templates/articl/index.html
{%extends "mainApp/wraper.html"%}
{%block title%}
{{article.title}}
{%endblock%}


{%block content%}
<div class="conteiner">

       
       

        <h3>{{article.title}}</h3>
        <p>
            {{article.text|capfirst}}
            
        </p>
        <img class="img" src="{{article.image.url}}" alt=""> 
        
        
       
        
        <h5>{{article.date|date:"d:m:Y"}}</h5>
       
      

{%for c in coments%}
        <h2>{{c.autor_name}}</h2>     
        <p>{{c.text}}</p>             
{%endfor%}

<form action="{% url 'articl:leave_coment' article.id %}" method="POST">
    {% csrf_token %}

    <input type="text" required placeholder="Ваше імя" name="name"><br>
    <textarea name="text" placeholder="Текст коментаря" cols="30" rows="10"></textarea><br>
    <button type="submit">Залишити коментярій</button>
</form>
</div>
{%endblock%}

category/templates/category/category.html
{%extends "mainApp/wraper.html"%}
{%block title%}
{{category.title}}
{%endblock%}


{%block content%}
<div class="conteiner">
<div class="category">
   
    <div class="inner">
        <div class="">
        <img class="img" src="{{category.image.url}}" alt=""> 
    </div>
    <div class="">
    <h3>{{category.title}}</h3>
    <p>{{category.text}}</p>
        </div>
    </div>
    
</div>
{%for post in article%}
       
       

        <a href="{% url 'articl:index' post.id %}"><h3>{{post.title}}</h3></a>
        <p>
            {{post.text|truncatewords:20 |capfirst}}
            ...
        </p>
        <img class="img" src="{{post.image.url}}" alt=""> 
        
        
       
        
        <h5>{{post.date|date:"d:m:Y"}}</h5>
       
        {%endfor%}
    </div>
{%endblock%}

category/templates/category/inculudes/category.html
{%block category%}

       
   

<a href=""><h3>{{category.title}}</h3></a>




        {%endblock%}

category/templates/category/index.html
{%extends "mainApp/wraper.html"%}
{%block title%}
Категорії
{%endblock%}


{%block content%}
<div class="conteiner">
<div class="category">
    {%for cat in category%}
    <div class="inner">
        <div class="">
        <img class="img" src="{{cat.image.url}}" alt=""> 
    </div>
    <div class="">
    <a href="{% url 'category:category_detal' cat.id %}"><h3>{{cat.title}}</h3></a>
    <p>{{cat.text}}</p>
        </div>
    </div>
    {%endfor%}
</div>

</div>
{%endblock%}

mainApp/templates/mainApp/inculudes/category.html
{%block category%}

       
   

<a href=""><h3>{{category.title}}</h3></a>




        {%endblock%}

mainApp/templates/mainApp/index.html
{%extends "mainApp/wraper.html"%}
{%block title%}
Головна
{%endblock%}


{%block content%}
<div class="conteiner">
<section class="content">
    
    <section class="main_content">
       
       
            <h3 class="slider__block_text">Заголовок</h3>
            <a class="slider__block_btn" href="">Найкращі статі</a>
            <div class="category">
                {%for cat in category%}
                <div class="inner">
                    <div class="">
                    <img class="img" src="{{cat.image.url}}" alt=""> 
                </div>
                <div class="">
                <a href="{% url 'category:category_detal' cat.id %}"><h3>{{cat.title}}</h3></a>
                <p>{{cat.text}}</p>
                    </div>
                </div>
                {%endfor%}
            </div>

            <form action="{% url 'mainApp:leave_email'%}" method="POST" class="form">
                {% csrf_token %}
            
                <input type="text" required placeholder="Ваше імя" name="name"><br>
                <input type="text" required placeholder="Ваше прізвище" name="surname"><br>
                <input type="email" required placeholder="Ваш email" name="email"><br>
                
                <button type="submit">Залишити коментярій</button>
            </form>
    </section>
    <section class="widget">
        {%for post in articl%}
       
       

        <a href="{% url 'articl:index' post.id %}"><h3>{{post.title}}</h3></a>
        <p>
            {{post.text|truncatewords:20 |capfirst}}
            ...
        </p>
        <img class="img" src="{{post.image.url}}" alt=""> 
        
        
       
        
        <h5>{{post.date|date:"d:m:Y"}}</h5>
       
        {%endfor%}
    </section>

</section>
</div>
{%endblock%}

mainApp/templates/mainApp/wraper.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%load static%}
    
    <link rel="stylesheet" href="{% static 'mainApp/css/Style.css'%}">
    <title>
        {%block title%}
        Сторніка
        {%endblock%}
       
    </title>
</head>

<body>
    <header class="header">
        <div class="conteiner">
            <div class="header__inner">
                <img src="" alt="" class="header__logo">
                <ul class="nav">
                    <li><a href="/">Головна</a></li>
                    <li><a href="{% url 'category:index' %}">Категорії</a></li>
                    <li><a href="">Топ</a></li>
                </ul>
            </div>
        </div>
    </header>
    {%block content%}
    
    {%endblock%}
    <footer class="footer">
        <div class="conteiner">
            <div class="footer__inner">
                <ul class="nav">
                    <li><a href="">Головна</a></li>
                    <li><a href="">Категорії</a></li>
                    <li><a href="">Топ</a></li>
                </ul>
                <p class="footer_txt">2020</p>
            </div>
        </div>
    </footer>
</body>

</html>